pipeline {
    //options {
        // set a timeout of 30 minutes for this pipeline
      //  timeout(time: 30, unit: 'MINUTES')
    //}
    //tools {
     //maven 'mvn'
     //}
    agent {
      label 'maven'
    }
     environment {
        giturl = "https://github.com/skadian2309/example-health-jee-openshift.git"
        projectName = "sumitkadian-11249"
      }  

    stages {
        stage('Build App') {        
           steps {
              git url: env.giturl
              script{      
                  sh "cd example-health-api;mvn install -DskipTests=true"    
              }
            }
           }    

        stage('Step1') {
            steps {
                script {
                    openshift.withCluster() {
                        openshift.withProject() {
                                echo "stage 1: using project: ${openshift.project()} in cluster ${openshift.cluster()}"
                        }
                    }
                }
            }
        }
        stage('stage 2') {
         steps {
            sh 'echo hello from stage 2!'
         }
        }

        stage('stage 3') {
            steps {
                sh 'echo hello from stage 3!. This is the last stage...'
            }
        }

    }
}
